//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eureka.CoinTrade.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eureka.CoinTrade.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 At Least One Exchange! 的本地化字符串。
        /// </summary>
        public static string AtLeastOneExchange {
            get {
                return ResourceManager.GetString("AtLeastOneExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorize Fail 的本地化字符串。
        /// </summary>
        public static string AuthorizeFail {
            get {
                return ResourceManager.GetString("AuthorizeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Info: Begin background query trade pair {2}&apos;s {0} information...  的本地化字符串。
        /// </summary>
        public static string BeginDownladDataAsync {
            get {
                return ResourceManager.GetString("BeginDownladDataAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Order Info: Cancel Order id {1} from exchange{0} has exception: {2} 的本地化字符串。
        /// </summary>
        public static string CancelOrderException {
            get {
                return ResourceManager.GetString("CancelOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Order Info: Cancel order id {1} from exchange {0} Fail, info:{2} 的本地化字符串。
        /// </summary>
        public static string CancelOrderFail {
            get {
                return ResourceManager.GetString("CancelOrderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Order Info: Cancel order id {1} from exchange {0} success. 的本地化字符串。
        /// </summary>
        public static string CancelOrderSuccess {
            get {
                return ResourceManager.GetString("CancelOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Option 的本地化字符串。
        /// </summary>
        public static string ConfigOption {
            get {
                return ResourceManager.GetString("ConfigOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Other Option 的本地化字符串。
        /// </summary>
        public static string ConfigOtherOption {
            get {
                return ResourceManager.GetString("ConfigOtherOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Info: Query {2}&apos;s {0} info from exchange {1} error, Async error: {3} 的本地化字符串。
        /// </summary>
        public static string DownloadDataAsyncError {
            get {
                return ResourceManager.GetString("DownloadDataAsyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software has expired, your expire date: 的本地化字符串。
        /// </summary>
        public static string ExpiredInfo {
            get {
                return ResourceManager.GetString("ExpiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fee 的本地化字符串。
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fund 的本地化字符串。
        /// </summary>
        public static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Code Not Match 的本地化字符串。
        /// </summary>
        public static string MachineCodeNotMatch {
            get {
                return ResourceManager.GetString("MachineCodeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Machine Code Not Match, Your Machine Code: 的本地化字符串。
        /// </summary>
        public static string MachineCodeNotMatchInfo {
            get {
                return ResourceManager.GetString("MachineCodeNotMatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Error 的本地化字符串。
        /// </summary>
        public static string MonitorState_DataError {
            get {
                return ResourceManager.GetString("MonitorState_DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Triggered 的本地化字符串。
        /// </summary>
        public static string MonitorState_NotTriggered {
            get {
                return ResourceManager.GetString("MonitorState_NotTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string MonitorState_Pause {
            get {
                return ResourceManager.GetString("MonitorState_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor Start 的本地化字符串。
        /// </summary>
        public static string MonitorState_Start {
            get {
                return ResourceManager.GetString("MonitorState_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor Stoped 的本地化字符串。
        /// </summary>
        public static string MonitorState_Stop {
            get {
                return ResourceManager.GetString("MonitorState_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triggered 的本地化字符串。
        /// </summary>
        public static string MonitorState_Triggered {
            get {
                return ResourceManager.GetString("MonitorState_Triggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api Key Info: Your never config Exchange {0}&apos;s Api Key, Function {1} Can not work. 的本地化字符串。
        /// </summary>
        public static string NoApiKeyCantWork {
            get {
                return ResourceManager.GetString("NoApiKeyCantWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find license file cointrade.key, Please contact service@ee-studio.com for this file！ 的本地化字符串。
        /// </summary>
        public static string NoCoinTradeKey {
            get {
                return ResourceManager.GetString("NoCoinTradeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No License 的本地化字符串。
        /// </summary>
        public static string NoLicense {
            get {
                return ResourceManager.GetString("NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Browser Issue, May can&apos;t view  Chart! 的本地化字符串。
        /// </summary>
        public static string NoteChartEx {
            get {
                return ResourceManager.GetString("NoteChartEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Note: This Exchange Not Support Open Orders Query) 的本地化字符串。
        /// </summary>
        public static string NoteNotSupportOpenOrders {
            get {
                return ResourceManager.GetString("NoteNotSupportOpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Note Status Bar, Information from Software Show Here. 的本地化字符串。
        /// </summary>
        public static string NoteStatusbar {
            get {
                return ResourceManager.GetString("NoteStatusbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Orders 的本地化字符串。
        /// </summary>
        public static string OpenOrders {
            get {
                return ResourceManager.GetString("OpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Order Success  的本地化字符串。
        /// </summary>
        public static string OrderSuccess {
            get {
                return ResourceManager.GetString("OrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade Pair Selected 的本地化字符串。
        /// </summary>
        public static string PairSelected {
            get {
                return ResourceManager.GetString("PairSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Alert 的本地化字符串。
        /// </summary>
        public static string PauseAlert {
            get {
                return ResourceManager.GetString("PauseAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Time 的本地化字符串。
        /// </summary>
        public static string PeriodType_AllTime {
            get {
                return ResourceManager.GetString("PeriodType_AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 Days 的本地化字符串。
        /// </summary>
        public static string PeriodType_Days10 {
            get {
                return ResourceManager.GetString("PeriodType_Days10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 Days 的本地化字符串。
        /// </summary>
        public static string PeriodType_Days2 {
            get {
                return ResourceManager.GetString("PeriodType_Days2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 Days 的本地化字符串。
        /// </summary>
        public static string PeriodType_Days5 {
            get {
                return ResourceManager.GetString("PeriodType_Days5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 Month 的本地化字符串。
        /// </summary>
        public static string PeriodType_Month1 {
            get {
                return ResourceManager.GetString("PeriodType_Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 Months 的本地化字符串。
        /// </summary>
        public static string PeriodType_Months3 {
            get {
                return ResourceManager.GetString("PeriodType_Months3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 Months 的本地化字符串。
        /// </summary>
        public static string PeriodType_Months6 {
            get {
                return ResourceManager.GetString("PeriodType_Months6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string PeriodType_Today {
            get {
                return ResourceManager.GetString("PeriodType_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year To Date 的本地化字符串。
        /// </summary>
        public static string PeriodType_YearToDate {
            get {
                return ResourceManager.GetString("PeriodType_YearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select Exchange! 的本地化字符串。
        /// </summary>
        public static string PleaseSelectExchange {
            get {
                return ResourceManager.GetString("PleaseSelectExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select First Exchange! 的本地化字符串。
        /// </summary>
        public static string PleaseSelectFirstExchange {
            get {
                return ResourceManager.GetString("PleaseSelectFirstExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select Second Exchange! 的本地化字符串。
        /// </summary>
        public static string PleaseSelectSecondExchange {
            get {
                return ResourceManager.GetString("PleaseSelectSecondExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select Show Color! 的本地化字符串。
        /// </summary>
        public static string PleaseSelectShowColor {
            get {
                return ResourceManager.GetString("PleaseSelectShowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select Trade Pair！ 的本地化字符串。
        /// </summary>
        public static string PleaseSelectTradePair {
            get {
                return ResourceManager.GetString("PleaseSelectTradePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buy Price 的本地化字符串。
        /// </summary>
        public static string PriceType_Buy {
            get {
                return ResourceManager.GetString("PriceType_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Price 的本地化字符串。
        /// </summary>
        public static string PriceType_High {
            get {
                return ResourceManager.GetString("PriceType_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Price 的本地化字符串。
        /// </summary>
        public static string PriceType_Last {
            get {
                return ResourceManager.GetString("PriceType_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Price 的本地化字符串。
        /// </summary>
        public static string PriceType_Low {
            get {
                return ResourceManager.GetString("PriceType_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sell Price 的本地化字符串。
        /// </summary>
        public static string PriceType_Sell {
            get {
                return ResourceManager.GetString("PriceType_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Info: Query {1}&apos;s {0} info has exception: {2} 的本地化字符串。
        /// </summary>
        public static string QueryDataException {
            get {
                return ResourceManager.GetString("QueryDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Info: Query {1}&apos;s {0} info success. 的本地化字符串。
        /// </summary>
        public static string QueryDataSuccess {
            get {
                return ResourceManager.GetString("QueryDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Fund 的本地化字符串。
        /// </summary>
        public static string QueryFund {
            get {
                return ResourceManager.GetString("QueryFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quotation 的本地化字符串。
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate Index Info: Begin Query {1}&apos;s Rate info from {0} ... 的本地化字符串。
        /// </summary>
        public static string RateInfoBeginQuery {
            get {
                return ResourceManager.GetString("RateInfoBeginQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate Index Info: Query{1}&apos;s rate info from {0} has exception: {2} 的本地化字符串。
        /// </summary>
        public static string RateInfoQueryException {
            get {
                return ResourceManager.GetString("RateInfoQueryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate Index Info: Query {1}&apos;s rate info from {0} fail, Async Error:{2} 的本地化字符串。
        /// </summary>
        public static string RateInfoQueryFail {
            get {
                return ResourceManager.GetString("RateInfoQueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate Index Info: Query{1}&apos;s rate info from {0} success, Rate is {2} 的本地化字符串。
        /// </summary>
        public static string RateInfoQuerySuccess {
            get {
                return ResourceManager.GetString("RateInfoQuerySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume Alert 的本地化字符串。
        /// </summary>
        public static string ResumeAlert {
            get {
                return ResourceManager.GetString("ResumeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Info: Submit order to{0} has exception: {1} 的本地化字符串。
        /// </summary>
        public static string SubmitOrderException {
            get {
                return ResourceManager.GetString("SubmitOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Info: Submit order success, order id {1} ,feedback from {0}: {2} 的本地化字符串。
        /// </summary>
        public static string SubmitOrderSuccess {
            get {
                return ResourceManager.GetString("SubmitOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Info: Submit order Fail, order id{1}, fail info:{2} 的本地化字符串。
        /// </summary>
        public static string SumbitOrderFail {
            get {
                return ResourceManager.GetString("SumbitOrderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take effect after restart！ 的本地化字符串。
        /// </summary>
        public static string TakeEffectAfterRestart {
            get {
                return ResourceManager.GetString("TakeEffectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ticker 的本地化字符串。
        /// </summary>
        public static string Ticker {
            get {
                return ResourceManager.GetString("Ticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade History 的本地化字符串。
        /// </summary>
        public static string TradeHistory {
            get {
                return ResourceManager.GetString("TradeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Info: Query {2}&apos;s {0} info from exchange {1} has exception : {3} 的本地化字符串。
        /// </summary>
        public static string UpdateDataException {
            get {
                return ResourceManager.GetString("UpdateDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Info: Query {2}&apos;s {0} info from exchange {1} success. 的本地化字符串。
        /// </summary>
        public static string UpdateDataSuccess {
            get {
                return ResourceManager.GetString("UpdateDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn Info 的本地化字符串。
        /// </summary>
        public static string WarnInfo {
            get {
                return ResourceManager.GetString("WarnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Api Keys have been saved in file &quot;Api.key&quot;. 的本地化字符串。
        /// </summary>
        public static string YourKeySaved {
            get {
                return ResourceManager.GetString("YourKeySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Never Select Any Pair in Exchange{0} Function {1} not work 的本地化字符串。
        /// </summary>
        public static string YourNeverSelectAnyPairInExchage {
            get {
                return ResourceManager.GetString("YourNeverSelectAnyPairInExchage", resourceCulture);
            }
        }
    }
}
